/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Benedikt
 */
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Gui extends javax.swing.JFrame {
    Main main;

    /**
     * Creates new form Gui
     */
    public Gui(Main main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnStarten = new javax.swing.JButton();
        panelEingabe = new javax.swing.JPanel();
        lblIp = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        btnVerbinden = new javax.swing.JButton();
        radioHost = new javax.swing.JRadioButton();
        radioClient = new javax.swing.JRadioButton();
        lblVerbunden = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStarten.setText("Starten");

        panelEingabe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIp.setText("IP Adresse");

        lblPort.setText("Port");

        txtIp.setText("IP Addresse");

        txtPort.setText("Port");

        btnVerbinden.setText("Verbinden");
        btnVerbinden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerbindenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEingabeLayout = new javax.swing.GroupLayout(panelEingabe);
        panelEingabe.setLayout(panelEingabeLayout);
        panelEingabeLayout.setHorizontalGroup(
            panelEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEingabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIp)
                    .addComponent(lblPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIp)
                    .addComponent(txtPort))
                .addContainerGap())
            .addGroup(panelEingabeLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnVerbinden, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        panelEingabeLayout.setVerticalGroup(
            panelEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEingabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIp)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVerbinden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(radioHost);
        radioHost.setText("Host");
        radioHost.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioHostStateChanged(evt);
            }
        });
        radioHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHostActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioClient);
        radioClient.setText("Client");
        radioClient.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioClientStateChanged(evt);
            }
        });

        lblVerbunden.setText("nicht Verbunden");

        jLabel1.setFont(new java.awt.Font("PhrasticMedium", 0, 36)); // NOI18N
        jLabel1.setText("pong3D");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioHost)
                        .addGap(104, 104, 104)
                        .addComponent(radioClient))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVerbunden, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnStarten, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioHost)
                    .addComponent(radioClient))
                .addGap(18, 18, 18)
                .addComponent(panelEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerbunden, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStarten, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHostActionPerformed
        if (radioHost.isSelected()) {
            main.createServer(Integer.parseInt(txtPort.getText()));
        
        }
        if (radioClient.isSelected()) {
            main.createClient(txtIp.getText(), Integer.parseInt(txtPort.getText()));
        }
    }//GEN-LAST:event_radioHostActionPerformed

    private void btnVerbindenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerbindenActionPerformed
       
        


// TODO add your handling code here:
    }//GEN-LAST:event_btnVerbindenActionPerformed

    private void radioHostStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioHostStateChanged
        // TODO add your handling code here:
        if(radioHost.isSelected()) {
        txtIp.setEditable(false);    
        try {    
            txtIp.setText(getIp());
            } catch (UnknownHostException ex) {
                Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_radioHostStateChanged

    private void radioClientStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioClientStateChanged
       if (radioHost.isSelected()) {
       txtIp.setEditable(true);
       txtIp.setText("IP Adresse");
       }
    }//GEN-LAST:event_radioClientStateChanged

    private String getIp() throws UnknownHostException {
    InetAddress ip = InetAddress.getLocalHost();
    return ip.toString();
    } 
    
    public void setConnection(boolean verbunden){
    if(verbunden){
    lblVerbunden.setText("Verbunden");
    
    }
    if(!verbunden){
    lblVerbunden.setText("Nicht verbunden");
    }
    
    }
    
    
    /**
     * @param args the command line arguments
     */

   /* public static void main(String args[]) {
        *//* Set the Nimbus look and feel *//*
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        *//* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        *//* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui(main).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStarten;
    private javax.swing.JButton btnVerbinden;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblVerbunden;
    private javax.swing.JPanel panelEingabe;
    private javax.swing.JRadioButton radioClient;
    private javax.swing.JRadioButton radioHost;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
